"""creat db

Revision ID: 8f0b81295e8c
Revises: 
Create Date: 2018-09-10 09:33:08.916483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0b81295e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('versionid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appinfo_id'), 'appinfo', ['id'], unique=False)
    op.create_index(op.f('ix_appinfo_version'), 'appinfo', ['version'], unique=False)
    op.create_index(op.f('ix_appinfo_versionid'), 'appinfo', ['versionid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appinfo_versionid'), table_name='appinfo')
    op.drop_index(op.f('ix_appinfo_version'), table_name='appinfo')
    op.drop_index(op.f('ix_appinfo_id'), table_name='appinfo')
    op.drop_table('appinfo')
    # ### end Alembic commands ###
